version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - /srv/dev-disk-by-uuid-485c8266-0849-4fb7-992f-3c143e4bfb73/containers/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      PUID: 911
      PGID: 993
      